#!/bin/bash
if [ ! -f /secure/ssl/mail.crt ]; then
    mkdir -p /secure/ssl && cd /secure/ssl
    openssl genrsa -out mail.key 2048
    openssl req -new -key mail.key -out mail.csr -subj "/C=XX/L=XX/O=XX/CN=domain.tld"
    openssl x509 -req -days 3650 -in mail.csr -signkey mail.key -out mail.crt
fi
