#!/bin/bash
/opt/bin/config-apply /opt/config/postfix/main.cf /etc/postfix/main.cf
echo "127.0.0.1  $POSTFIX_HOSTNAME" >> /etc/hosts

/opt/bin/gentls
mkdir -p /secure/postfix
mkdir -p /secure/dovecot
touch /secure/postfix/vmaps && postmap /secure/postfix/vmaps
touch /secure/postfix/vuids && postmap /secure/postfix/vuids
touch /secure/postfix/vgids && postmap /secure/postfix/vgids
touch /secure/postfix/vhosts
touch /secure/dovecot/users
touch /secure/dovecot/passwd
newaliases

supervisorctl start rsyslog
supervisorctl start crond
supervisorctl start opendmarc
supervisorctl start postfix:master
supervisorctl start dovecot
