#!/bin/bash
/opt/bin/config-apply /opt/config/postfix/main.cf /etc/postfix/main.cf
/opt/bin/config-apply /opt/config/postfix/vhosts /etc/postfix/vhosts
/opt/bin/config-apply /opt/config/postfix/vmaps /etc/postfix/vmaps

/opt/bin/gentls
mkdir -p /secure/postfix
mkdir -p /secure/dovecot
postmap /secure/postfix/vmaps
postmap /secure/postfix/vuids
postmap /secure/postfix/vgids

supervisorctl start rsyslog
supervisorctl start crond
supervisorctl start opendmarc
supervisorctl start postfix:master
supervisorctl start dovecot
